# Generated by Django 3.0.1 on 2019-12-31 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('data_pagamento', models.DateField()),
                ('descricao', models.TextField()),
                ('entrega', models.BooleanField(default=False)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
