# Generated by Django 3.0.1 on 2019-12-31 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('razao_social', models.CharField(max_length=45)),
                ('cpf_cnpj', models.CharField(max_length=18)),
                ('email', models.CharField(max_length=45)),
                ('telefone', models.CharField(max_length=45)),
                ('responsavel', models.CharField(max_length=45)),
            ],
        ),
    ]
