# Generated by Django 3.0.1 on 2020-02-04 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrega',
            old_name='taxa_entrega',
            new_name='valor',
        ),
    ]
