# Generated by Django 3.0.1 on 2020-02-16 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='estabelecimento',
        ),
    ]
