# Generated by Django 3.0.1 on 2020-01-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200105_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rota_cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
