# Generated by Django 3.0.1 on 2020-02-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200204_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='valor',
            field=models.FloatField(),
        ),
    ]
