# Generated by Django 3.0.1 on 2019-12-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_estabelecimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_entrega', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
