# Generated by Django 3.0.1 on 2020-01-06 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rota_cliente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rota_cliente',
            new_name='Cliente_rota',
        ),
    ]
