# Generated by Django 3.0.1 on 2020-02-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200204_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
