# Generated by Django 3.0.1 on 2020-01-06 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200106_0139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente_rota',
        ),
    ]
