# Generated by Django 3.0.1 on 2019-12-31 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddd', models.CharField(max_length=3)),
                ('numero', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='descricao',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
