# Generated by Django 3.0.1 on 2020-01-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_cliente_rota'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rota',
            field=models.ManyToManyField(to='myapp.Rota'),
        ),
    ]
