# Generated by Django 3.0.1 on 2020-01-02 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20191231_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefone',
            name='cliente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.Cliente'),
        ),
    ]
