# Generated by Django 3.0.1 on 2020-01-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta_receber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
