# Generated by Django 3.0.1 on 2020-01-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_pedido_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estabelecimento',
            field=models.ManyToManyField(to='myapp.Estabelecimento'),
        ),
    ]
