# Generated by Django 3.0.1 on 2020-01-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_cliente_estabelecimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='funcionalidade',
            field=models.ManyToManyField(to='myapp.Funcionalidade'),
        ),
    ]
