# Generated by Django 3.0.1 on 2020-01-04 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_funcionalidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='item',
            name='entrega',
        ),
    ]
